### ISSUE TITLE
my response

### ISSUE THREAD

**Issue by VillainsRule4000** [intertransfer/god#1]
> He DDoSed us (Blacket) with Replit IPs and slowed down our server until it crashed.  

I wasn't coding any of these exploits nor have I done any major things to ddos it, that has been other members - check the leaderboard if you need help figuring out who.
I was running one repl at 200ms opening last night.

> He cut me off, banned me everywhere

I believe I banned you from one place, my server. I did not unfriend you or block you.

> This is immature and stupid, and all for a reason he should've expected, him slowing down our server by ddosing it. It's crazy.

Referencing back, I am not ddosing the Blacket servers.

> Now he should've expected this, considering he was DDoSing us until he got a glitched, negative count of tokens. Who wouldn't ban someone for that?

An example of someone with negative tokens is @Corn on blacket. it's not hard, im not the first and I won't be the last.

> braindead robot fans

I got "fans" from being kind to the community, hosting giveaways, dealing with forms and just being generally active. if the community likes me, they do.

> try to convince everyone that I'm an awful person.

they already think you're awful because of autoban and other stuff.
that's not an influence of "me"

> cut ties with him until he learns to stop being petty.

I thought I cut all the ties?

I'd like to have the unobfuscated BlacketWare scripts. I spent a good amount of time on them and don't like to see my work stolen like this.

**Comment by intertransfer** [comment]
great its this again! xotic will be here soon.

> I wasn't coding any of these exploits nor have I done any major things to ddos it, that has been other members > - check the leaderboard if you need help figuring out who.
> I was running one repl at 200ms opening last night.
We found that packs were being opened very rapidly at a delay of around 25ms, with your user ID and multiple IP addresses. You were the only account slowing down our server.

> I believe I banned you from one place, my server. I did not unfriend you or block you.
I look back on that statement and I did realize I screwed that up.

> Referencing back, I am not ddosing the Blacket servers.
You were, "referencing back" to our checked logs.

> An example of someone with negative tokens is @corn on blacket. it's not hard, im not the first and I won't be the last.
The only way to get negative tokens is to FUCKING DDOS US UNTIL THE SERVER CAN NO LONGER PROCESS TOKENS. This completely obliterates your original claims.

> I got "fans" from being kind to the community, hosting giveaways, dealing with forms and just being generally active. if the community likes me, they do.
The thing is, you don't even moderate well, and if you do, you abuse it. I ban people for actual spam and scams.

> they already think you're awful because of autoban and other stuff.
> that's not an influence of "me"
Really? Because I think not, since I convinced everyone I'm fine. Nobody's been false autobanned unless they were actually spamming YOUR BOT'S COMMANDS.

> I thought I cut all the ties?
And I cut ties with BlacketWare.

> I'd like to have the unobfuscated BlacketWare scripts. I spent a good amount of time on them and don't like to see my work stolen like this.
I'll send them to you on Discord. I never stole any work.

**Comment by VillainsRule4000** [comment]
will you give me a response to this?

**Comment by VillainsRule4000** [comment]
so I've put some thought into this (over math class)
I think you're right on some accounts.
I hope this doesn't mark the end of our friendship and we can work this out together.

**Comment by intertransfer** [comment]
> will you give me a response to this?

ok
